project:
  type: website
  output-dir: docs

website:
  title: "GitHub Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Resume.qmd
        text: Resume
      - href: My blog.qmd
        text: Blog
      - href: Contact.qmd
        text: Contact
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

