---
title: "Resume"
---

# Education

* Bachelor of Arts in Economics, 2016 

# Current Position

#### Elmwood Community Correspondent (Freelance), Free Press Community Review East, June 2023 - Present

* I am responsible for contributing a column on Elmwood, about monthly, to the Free Press Community Review. I come up with engaging hyper-local stories, making use of diverse sources including public documents, census and other statistical data, and key informant interviews.

# Previous Positions

#### Policy Analyst and Project Manager, Waapihk Research Group, March 2019 - April 2024

* Responsible, in a leading or supporting role, for the development of various reports, briefs, and other written research products for clients. Participate in team meetings to ensure there is shared understanding of project objectives and helped brainstorm solutions to unforeseen project developments and roadblocks. Research focused in the health policy field, social sectors, and fiscal analysis and program costing for Indigenous peoples, primarily focused on-reserve.

#### West Broadway Community Correspondent (Freelance), Free Press Community Review East, June 2020 - April 2023

* I was responsible for contributing a column on West Broadway, about monthly, to the Free Press Community Review. I came up with engaging hyper-local stories and wove a variety of sources, including public documents, stakeholder interviews, and statistics together to create compelling narratives.

* My time as West Broadway Community Correspondent overlapped with the COVID-19 pandemic. I wrote about the effects of the pandemic on businesses and individuals in West Broadway, with some particular focus on impacts on renters.

#### Policy Analyst, Western Economic Diverisfication Canada (Now Prairies Economic Development Canada), February 2018 - February 2019

* One year term position with Western Economic Diversification Canada. In this role, I prepared research and analysis on relevant issues relating to economic development for Western Canada, Manitoba and various communities. This included reading through policy literature, coordinating work with other analysts and working with data. 

#### City Report, The Uniter, April 2017 - December 2017

* I wrote stories for the City section in The Uniter, as the designated City Reporter. These touched on a number of policy, political and community matters at the neighbourhood, city-wide, provincial and national levels.

#### Research Assistant, University of Winnipeg, June 2017 to December 2017

* I worked at the University of Winnipeg's Institute of Urban Studies. I helped with research on Housing First, an innovative program model for delivering services to the homeless population. This included analysis of the At Home/Chez Soi project in Winnipeg, the significant role Indigenous community organizations played in delivering services, and other Housing First programs. My work involved qualitative research coding, transcribing, environmental scanning, and report writing.

#### Research Assistant, Winnipeg Regional Health Authority, June 2016 - September 2016

* I assisted with various research projects projects related to organizational change and evaluation in the area of health equity promotion. Conducted literature reviews, wrote internal reports, contributed to newsletters, designed surveys and analyzed survey data. Presented findings in meetings.
